apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api-deployment
  labels:
    app: todo-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
      - name: todo-api
        image: foued86/todo-api:1.0
        ports:
          - containerPort: 8080
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: app-configmap
                key: db_host            
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: app-configmap
                key: db_port            
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: app-configmap
                key: db_name           
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: app-configmap
                key: db_user         
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-password
                key: db_password
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: app-configmap
                key: port       
