apiVersion: v1
kind: Service
metadata:
  name: todo-api-service
  labels:
    app: todo-api
spec:
  type: NodePort
  selector:
    app: todo-api
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31231
